/*

Problem 44:

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their 
sum and difference are pentagonal and D = |Pk − Pj| is minimised; 

what is the value of D?
*/

pub fn pentagonal(n: i64) -> i64 {
  (n * (3 * n -1) ) / 2
}

fn is_pentagonal(n: i64)-> bool {
    let r = ((1 + 24 * n) as f64).sqrt() as i32;
    r % 6 == 5
}



#[cfg(test)]
mod tests {
  use pentagonal;
  use is_pentagonal;

    #[test]
    fn pentatagonal_5() {
        assert_eq!(pentagonal(5),35);
    }

    #[test]
    fn all_pentatagonal() {
      let ps = (1..10).map(|x| pentagonal(x))
                      .collect::<Vec<_>>();
      assert!(ps.iter().all(|&x| is_pentagonal(x)));

    }
}
