/*

Problem 45: 

Triangle, pentagonal, and hexagonal numbers are generated by 
the following formulae:

Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	    1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal 
and hexagonal.

*/

pub fn triangle(n: i64) -> i64 {
    (n * (n + 1)) / 2
}

pub fn pentagonal(n: i64) -> i64 {
    (n * (3 * n - 1)) / 2
}

pub fn hexagonal(n: i64) -> i64 {
    n * (2 * n - 1)
}
 

#[cfg(test)]
mod tests {
    use triangle;
    use hexagonal;
    use pentagonal;

    #[test]
    fn equal_values() {
        assert_eq!(triangle(285) == pentagonal(165) && 
                    pentagonal(165) == hexagonal(143), true);
    }
}
